name: Linux x64

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Apt Update
      run: sudo apt update
    - name: Apt Install
      run: sudo apt-get install -y -q  build-essential
    - name: Get Submodules
      run: ./get_dlc
    - name: Compile
      run: ./make --compile --debug
    - name: Run Tests
      run: ./bin/soso
