name: macOS

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v2
    - name: Get Submodules
      run: ./get_dlc
    - name: Compile
      run: ./make --compile --debug
    - name: Run Tests
      run: ./bin/soso
