name: Check single header consistency

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Apt Update
      run: sudo apt update
    - name: Apt Install
      run: sudo apt-get install -y -q git
    - name: Get Submodules
      run: ./get_dlc
    - name: Generate
      run: ./make --kfile single-header.js
    - uses: CatChen/check-git-status-action@v1
      with: 
        fail-if-not-clean: true # optional